import csv
import random

# -------- Templates --------
positive_templates = [
    "Love this! {}",
    "So glad to see this! {}",
    "Brilliant work! {}"
]

negative_templates = [
    "Hate this. {}",
    "This is disappointing. {}",
    "Not a fan of this at all. {}"
]

# -------- Prompts (example: combine all your 10 topic lists here) --------
politics_prompts = [
    "a policy that prioritizes healthcare access for everyone",
    "leaders finally listening to public concerns",
    "real action being taken against corruption",
    "transparent decision-making in government",
    "investment in public education systems",
    "policies that protect workers’ rights",
    "lawmakers focusing on long-term impact over short-term gains",
    "steps toward reducing economic inequality",
    "evidence-based policymaking becoming the norm",
    "public funds being used responsibly",
    "inclusive policies that represent marginalized communities",
    "efforts to strengthen democratic institutions",
    "clear accountability from elected officials",
    "policies that support small businesses",
    "meaningful reforms instead of empty promises",
    "environmental considerations being taken seriously",
    "ethical standards being enforced in politics",
    "public interest placed above corporate influence",
    "laws that protect basic human rights",
    "government transparency improving",
    "policies designed with expert input",
    "leaders admitting mistakes and correcting course",
    "bipartisan cooperation on critical issues",
    "measures that strengthen social safety nets",
    "citizen voices influencing policy outcomes",
    "decisions being made without public consultation",
    "policies that benefit a small elite",
    "lack of accountability for misconduct",
    "important reforms being endlessly delayed",
    "misinformation shaping public policy",
    "basic rights being treated as negotiable",
    "policies driven by political theater",
    "short-term fixes replacing real solutions",
    "public resources being mismanaged",
    "science being ignored in policy decisions",
    "opaque processes behind major decisions",
    "vulnerable groups being overlooked",
    "corruption scandals without consequences",
    "policies favoring donors over citizens",
    "leaders avoiding responsibility",
    "public trust being taken for granted",
    "decisions made without data",
    "empty rhetoric replacing action",
    "inequality being downplayed by officials",
    "important voices being silenced",
    "regressive policies being reintroduced",
    "lack of empathy in governance",
    "policies that increase social division",
    "critical issues being politicized",
    "public welfare treated as a burden",
    "ethics being sacrificed for convenience",
    "accountability being selectively enforced",
    "citizens excluded from decision-making"
]

technology_ai_prompts = [
    "AI tools improving everyday productivity",
    "technology making complex tasks easier",
    "responsible AI development being prioritized",
    "automation helping people focus on creative work",
    "AI models becoming more transparent",
    "ethical guidelines shaping AI innovation",
    "technology improving accessibility for everyone",
    "AI assisting doctors with better diagnoses",
    "smart systems optimizing energy usage",
    "AI-powered tools enhancing education",
    "clear regulations for emerging technologies",
    "human-centered AI design principles",
    "technology closing gaps instead of widening them",
    "open-source contributions driving innovation",
    "AI being used to solve real-world problems",
    "unregulated AI systems being deployed",
    "technology replacing jobs without safeguards",
    "AI decisions lacking transparency",
    "data privacy being treated lightly",
    "overreliance on automation",
    "AI models trained on biased data",
    "tech companies prioritizing speed over safety",
    "lack of accountability in AI failures",
    "surveillance technologies expanding unchecked",
    "AI being used without user consent",
    "technology increasing social isolation",
    "algorithms reinforcing inequality",
    "poor communication about AI limitations",
    "security risks being ignored",
    "technology decisions made without public input",
    "AI hype overshadowing real capabilities",
    "ethical concerns being dismissed",
    "automation without reskilling plans",
    "opaque recommendation algorithms",
    "AI replacing human judgment too quickly",
    "technology rolling out without testing",
    "data collection without transparency",
    "AI misuse going unaddressed",
    "weak safeguards for sensitive data",
    "tech leaders avoiding responsibility",
    "AI systems failing without explanation",
    "innovation driven purely by profit",
    "technology advancing faster than regulation",
    "AI tools lacking clear accountability",
    "users treated as test subjects",
    "bias audits being ignored",
    "technology widening the digital divide",
    "AI deployed without ethical review",
    "shortcuts taken in AI safety",
    "automation decisions made without empathy",
    "technology shaping behavior without consent",
    "AI systems influencing opinions silently",
    "critical tech flaws being downplayed",
    "responsibility being shifted to users"
]

health_wellness_prompts = [
    "new initiatives making healthcare more accessible",
    "mental health programs being prioritized in communities",
    "fitness campaigns motivating people to stay active",
    "nutrition awareness efforts reaching wider audiences",
    "breakthroughs in disease prevention and treatment",
    "telemedicine improving access to care",
    "holistic wellness approaches being adopted",
    "vaccination drives protecting vulnerable populations",
    "wellness technology helping track personal health",
    "healthcare workers receiving better support",
    "programs reducing stress in workplaces",
    "public campaigns encouraging healthy lifestyles",
    "innovations in mental health therapy",
    "community programs promoting preventive care",
    "research improving treatment for chronic conditions",
    "poor access to affordable healthcare",
    "mental health stigma still widespread",
    "fitness programs being inaccessible to many",
    "nutritional guidance being ignored",
    "misinformation spreading about health topics",
    "healthcare inequalities persisting",
    "overworked medical staff facing burnout",
    "wellness apps failing to protect privacy",
    "chronic conditions being underfunded",
    "lack of support for mental wellness",
    "health policies favoring the wealthy",
    "preventive care being neglected",
    "poor public health communication",
    "dangerous health trends being promoted",
    "limited access to essential medications",
    "stress and anxiety rising globally",
    "insurance gaps leaving people unprotected",
    "healthcare innovation being slow",
    "wellness initiatives ignoring minorities",
    "lack of affordable mental health resources",
    "overemphasis on quick fixes instead of lifestyle changes",
    "poorly funded community health programs",
    "nutrition education being underprioritized",
    "health inequities growing wider",
    "exercise programs not accessible to everyone",
    "medical misinformation causing harm",
    "research underfunded for rare diseases",
    "health systems failing in emergencies",
    "workplace wellness programs being tokenistic",
    "preventive health measures ignored",
    "mental health initiatives lacking follow-up",
    "lack of integration between wellness programs",
    "public health campaigns being ineffective",
    "overreliance on supplements over lifestyle change",
    "healthcare systems being bureaucratic",
    "wellness trends causing confusion",
    "stress management programs underused",
    "inadequate care for chronic illness patients",
    "lack of support for caregivers",
    "inequalities in maternal and child health",
    "emergency preparedness being overlooked",
    "access to healthy food limited in many areas"
]

climate_environment_prompts = [
    "efforts to reduce carbon emissions gaining momentum",
    "renewable energy projects being implemented worldwide",
    "policies protecting endangered species",
    "innovations in sustainable agriculture",
    "community programs cleaning up local environments",
    "government commitments to fight climate change",
    "green technology making cities cleaner",
    "awareness campaigns encouraging recycling",
    "reforestation projects restoring natural habitats",
    "clean energy adoption improving air quality",
    "research driving climate adaptation strategies",
    "ocean conservation initiatives making progress",
    "eco-friendly policies being introduced in industries",
    "sustainable transportation options being promoted",
    "awareness about plastic pollution increasing",
    "lack of urgency in climate policy",
    "deforestation continuing at alarming rates",
    "carbon emissions still rising in many countries",
    "pollution affecting vulnerable communities",
    "environmental laws being ignored",
    "ineffective recycling systems",
    "wildlife habitats being destroyed",
    "lack of investment in clean energy",
    "greenwashing by large corporations",
    "poor enforcement of environmental regulations",
    "rising global temperatures causing concern",
    "climate disasters becoming more frequent",
    "fossil fuel dependency still high",
    "ocean pollution growing",
    "loss of biodiversity accelerating",
    "unsustainable agriculture harming ecosystems",
    "air quality deteriorating in urban areas",
    "environmental activism facing resistance",
    "inadequate funding for conservation projects",
    "public awareness not translating into action",
    "climate policy being delayed",
    "government ignoring scientific advice",
    "waste management systems failing",
    "energy efficiency standards being lax",
    "carbon offset programs lacking transparency",
    "environmental education underfunded",
    "industrial pollution unchecked",
    "endangered species at greater risk",
    "renewable energy incentives insufficient",
    "water scarcity affecting communities",
    "natural disaster preparedness lagging",
    "pollution affecting public health",
    "climate goals not being met",
    "deforestation policies weak",
    "plastic use remaining high despite campaigns",
    "inequality in environmental protection",
    "ecosystem restoration being underprioritized",
    "urban planning ignoring green spaces",
    "sustainable innovation facing barriers",
    "renewable energy adoption slow in some regions",
    "community engagement in climate action limited",
    "lack of accountability in environmental policies"
]

finance_crypto_prompts = [
    "new regulations improving market transparency",
    "cryptocurrency adoption growing responsibly",
    "financial literacy programs reaching more people",
    "innovations making banking more accessible",
    "policies supporting small investors",
    "blockchain technology improving transaction security",
    "initiatives protecting consumers from fraud",
    "financial technology simplifying payments",
    "investment education being prioritized",
    "cryptocurrency being integrated responsibly",
    "markets showing resilience after volatility",
    "programs helping people save and invest",
    "banks offering more ethical financial products",
    "transparent reporting improving investor trust",
    "financial innovation supporting economic growth",
    "lack of oversight in crypto markets",
    "fraudulent schemes exploiting investors",
    "extreme market volatility causing panic",
    "financial inequalities remaining high",
    "scams targeting inexperienced traders",
    "cryptocurrency hype outpacing regulation",
    "investor protections being ignored",
    "high-risk investments marketed irresponsibly",
    "banks failing to support small businesses",
    "misleading financial advice circulating",
    "poor transparency in financial reporting",
    "volatile crypto tokens causing losses",
    "lack of safeguards for digital assets",
    "unequal access to investment opportunities",
    "predatory lending practices continuing",
    "centralized control limiting financial freedom",
    "investor education being neglected",
    "crypto wallets being hacked frequently",
    "financial regulations lagging behind innovation",
    "market manipulation harming ordinary investors",
    "fees and hidden costs reducing accessibility",
    "risk management in finance being overlooked",
    "fraud in DeFi platforms",
    "speculative investments causing instability",
    "unequal financial literacy across populations",
    "financial markets being driven by hype",
    "lack of accountability for financial misconduct",
    "insider trading affecting fairness",
    "banking systems failing underserved communities",
    "crypto scams spreading faster than prevention",
    "unsustainable investment practices",
    "regulatory gaps putting investors at risk",
    "misuse of personal financial data",
    "market crashes affecting livelihoods",
    "crypto bubbles forming rapidly",
    "traditional finance ignoring innovation",
    "high fees limiting investment access",
    "lack of support for responsible investing",
    "financial inclusion still a major challenge",
    "misinformation affecting investment decisions",
    "technology-driven finance facing security challenges",
    "unstable currencies creating economic pressure",
    "market speculation causing anxiety"
]

sports_fitness_prompts = [
    "athletes breaking records with hard work",
    "new fitness programs helping people stay active",
    "community sports initiatives encouraging youth participation",
    "technology improving training and performance",
    "healthy lifestyle campaigns reaching more people",
    "teams showing great sportsmanship",
    "exercise routines becoming more accessible",
    "coaching programs mentoring young talent",
    "sports events promoting inclusivity",
    "innovations in sports safety equipment",
    "mental health being prioritized for athletes",
    "fitness challenges motivating communities",
    "nutrition programs supporting athlete performance",
    "adaptive sports programs expanding",
    "grassroots programs growing interest in sports",
    "injuries sidelining top athletes",
    "fitness programs being too expensive",
    "teams underperforming despite potential",
    "lack of access to sports facilities",
    "poor safety measures in training",
    "coaching programs being inconsistent",
    "athlete burnout due to overtraining",
    "youth programs lacking funding",
    "sports policies failing to protect players",
    "health risks ignored in competitions",
    "training programs not inclusive",
    "inadequate support for disabled athletes",
    "poor nutrition guidance for participants",
    "teams facing mismanagement issues",
    "fitness technology not accessible to all",
    "overemphasis on competition over wellness",
    "injury prevention programs underfunded",
    "lack of proper recovery protocols",
    "coaching ethics being questioned",
    "fitness classes not catering to beginners",
    "overcrowded sports facilities",
    "limited opportunities for women in sports",
    "sports programs focusing only on elite athletes",
    "youth losing interest due to lack of support",
    "mental health challenges ignored in teams",
    "training schedules being unrealistic",
    "safety regulations not enforced",
    "limited outdoor spaces for community sports",
    "inconsistent access to sports equipment",
    "underfunded recreational programs",
    "lack of awareness about physical health",
    "poor engagement in community sports",
    "nutrition education being overlooked",
    "coaching inconsistencies affecting performance",
    "fitness campaigns failing to reach everyone",
    "injury rehabilitation support lacking",
    "sports opportunities being unequal",
    "overemphasis on winning over wellness",
    "lack of mentorship for young athletes",
    "sports development programs underutilized",
    "inadequate facilities in schools",
    "fitness incentives not widely available"
]

entertainment_celebrity_prompts = [
    "a movie receiving well-deserved praise from critics",
    "an inspiring performance by a rising star",
    "TV shows promoting meaningful messages",
    "musicians using their platform for good causes",
    "award ceremonies celebrating real talent",
    "actors showing dedication to their craft",
    "films breaking stereotypes in storytelling",
    "celebrities raising awareness for social issues",
    "new content that engages audiences positively",
    "performances that leave audiences amazed",
    "innovative projects in the entertainment industry",
    "celebrity collaborations creating positive impact",
    "artists pushing creative boundaries",
    "movies highlighting important real-world themes",
    "entertainment bringing people together",
    "celebrity behavior that disappoints fans",
    "controversial statements by public figures",
    "overhyped movies failing to deliver",
    "award shows ignoring deserving talent",
    "poor treatment of artists behind the scenes",
    "films with weak storylines or messages",
    "celebrity scandals overshadowing achievements",
    "performances falling short of expectations",
    "overexposure of certain celebrities",
    "entertainment news focusing on negativity",
    "talent being overlooked in award decisions",
    "poorly executed marketing campaigns",
    "celebrity feuds causing unnecessary drama",
    "reboots failing to capture original magic",
    "fans disappointed by creative choices",
    "actors criticized unfairly for roles",
    "over-commercialization in music or film",
    "films neglecting representation",
    "media spreading misinformation about stars",
    "projects rushed to meet deadlines",
    "celebrities behaving irresponsibly",
    "overrated performances receiving awards",
    "TV shows canceled too early",
    "lack of support for emerging talent",
    "fans upset by changes to beloved franchises",
    "public image affecting perception unfairly",
    "films lacking originality",
    "entertainment trends causing fatigue",
    "celebrities ignoring social responsibility",
    "media focusing on gossip instead of work",
    "projects failing to respect cultural sensitivity",
    "performance quality not meeting expectations",
    "public statements generating backlash",
    "creative projects underfunded",
    "audiences disappointed by live shows",
    "celebrities engaging in harmful promotions",
    "streaming platforms prioritizing quantity over quality",
    "artists underappreciated for innovative work",
    "content creators facing unfair criticism",
    "entertainment sometimes ignoring real issues",
    "fans frustrated with industry practices"
]

education_careers_prompts = [
    "schools implementing innovative learning programs",
    "teachers being recognized for their dedication",
    "career programs helping students find their passion",
    "online courses expanding access to education",
    "mentorship opportunities guiding young professionals",
    "policies improving education quality",
    "training programs enhancing workplace skills",
    "students achieving impressive academic milestones",
    "programs reducing barriers to higher education",
    "innovative teaching methods engaging learners",
    "schools prioritizing mental health support",
    "workplace initiatives promoting career growth",
    "educational technology improving learning outcomes",
    "community programs supporting lifelong learning",
    "scholarships making education accessible",
    "underfunded schools struggling to meet needs",
    "students facing barriers to quality education",
    "mentorship programs lacking resources",
    "career development opportunities limited",
    "outdated curriculum affecting learning",
    "teachers overwhelmed by class sizes",
    "inequality in access to educational resources",
    "workplace training being inconsistent",
    "students dropping out due to lack of support",
    "professional guidance not reaching everyone",
    "educational policies failing to address real needs",
    "digital divide affecting learning outcomes",
    "underpaid educators",
    "programs ignoring marginalized communities",
    "job opportunities not keeping pace with skills",
    "career growth blocked by bureaucracy",
    "skills training not aligned with industry demands",
    "schools lacking proper facilities",
    "students under pressure without support",
    "mentorship opportunities being inaccessible",
    "training programs not inclusive",
    "educational resources being wasted",
    "careers limited by systemic issues",
    "learning environments lacking safety",
    "underfunded programs reducing quality",
    "students struggling without guidance",
    "workplace growth opportunities unevenly distributed",
    "educational innovation being slow",
    "teachers lacking professional development",
    "career support services underutilized",
    "students not receiving proper feedback",
    "resources concentrated in urban areas",
    "inequalities in access to technology",
    "professional advancement blocked by outdated policies",
    "learning methods not adapting to student needs",
    "job market challenges affecting graduates",
    "career mentorship unavailable for many",
    "educational programs failing to inspire",
    "skills development initiatives lacking support",
    "students discouraged by systemic obstacles",
    "workplace policies not supporting growth",
    "educational inequity limiting potential"
]

science_space_prompts = [
    "new discoveries expanding our understanding of the universe",
    "research breakthroughs improving healthcare outcomes",
    "scientists making important climate change findings",
    "space missions inspiring curiosity globally",
    "innovations in renewable energy technology",
    "scientific studies shedding light on complex problems",
    "astronomy projects revealing distant galaxies",
    "research improving environmental sustainability",
    "space exploration pushing technological boundaries",
    "science education initiatives reaching more students",
    "scientists collaborating across borders effectively",
    "new technologies advancing space travel",
    "data from experiments leading to critical insights",
    "research programs addressing pressing global issues",
    "scientific communication becoming more accessible",
    "lack of funding for important research",
    "scientific misinformation spreading rapidly",
    "space missions delayed due to technical issues",
    "research not being translated into action",
    "inequality in access to scientific education",
    "critical studies being ignored",
    "scientists facing obstacles in publishing work",
    "underfunded environmental research",
    "failed experiments causing setbacks",
    "space exploration projects canceled",
    "innovation slowed by bureaucracy",
    "scientific collaboration hindered by politics",
    "lack of public engagement with research",
    "important findings underreported",
    "technological failures affecting progress",
    "research not addressing real-world needs",
    "scientific data being misinterpreted",
    "experiments delayed due to lack of resources",
    "scientists underappreciated for their work",
    "space missions facing budget cuts",
    "research priorities not aligned with societal needs",
    "scientific studies being criticized unfairly",
    "innovation limited by regulations",
    "critical space research overlooked",
    "scientific debates being politicized",
    "data transparency being insufficient",
    "research infrastructure lacking support",
    "experiments producing inconclusive results",
    "scientists struggling with reproducibility issues",
    "space discoveries not widely publicized",
    "research collaborations breaking down",
    "funding being diverted from important science",
    "scientific literacy in society remains low",
    "technological advancements underutilized",
    "climate science being ignored by policymakers",
    "research not reaching marginalized communities",
    "experiments facing ethical challenges",
    "scientific publications being delayed",
    "space technology being underfunded",
    "innovation pipelines interrupted",
    "research ethics being questioned"
]

lifestyle_personal_dev_prompts = [
    "new habits improving daily productivity",
    "mindfulness practices reducing stress",
    "self-care routines making a real difference",
    "personal growth programs helping people achieve goals",
    "healthy lifestyle choices being adopted widely",
    "motivational content inspiring positive change",
    "time management strategies boosting efficiency",
    "wellness apps helping track progress effectively",
    "goal-setting workshops encouraging focus",
    "meditation practices improving mental clarity",
    "fitness routines integrated into busy schedules",
    "journaling helping people reflect and grow",
    "personal development books making an impact",
    "online courses fostering skill growth",
    "community support programs motivating change",
    "lack of consistency in self-improvement routines",
    "burnout despite lifestyle efforts",
    "motivational advice feeling generic or ineffective",
    "healthy habits being hard to maintain",
    "personal growth programs underdelivering",
    "wellness trends being overhyped",
    "time management tools being confusing",
    "lack of access to coaching or mentorship",
    "fitness routines being too demanding",
    "goal-setting advice feeling unrealistic",
    "self-care practices being ignored",
    "resources for personal development limited",
    "bad habits being hard to break",
    "online courses not engaging enough",
    "wellness programs being inaccessible",
    "lack of guidance for lifestyle changes",
    "motivational content feeling hollow",
    "personal growth efforts facing obstacles",
    "stress management programs underfunded",
    "self-improvement advice being inconsistent",
    "healthy routines interrupted by daily pressures",
    "overloaded schedules preventing personal growth",
    "limited support for mental wellness",
    "lifestyle apps failing to deliver results",
    "lack of community in self-improvement",
    "fitness goals being unrealistic",
    "motivation fading over time",
    "personal development workshops underutilized",
    "guidance for habit-building being inadequate",
    "wellness trends causing confusion",
    "self-care being treated as optional",
    "coaching programs lacking follow-up",
    "time management techniques underused",
    "mindset programs not inclusive",
    "resources for personal growth being uneven",
    "work-life balance programs being ignored",
    "self-improvement content overloaded",
    "healthy lifestyle advice inconsistent",
    "motivation hard to sustain over long periods",
    "personal development tools not practical",
    "lack of accountability in habit tracking",
    "wellness programs not reaching everyone"
]



# -------- Combine all prompts --------
all_prompts = (
    politics_prompts +
    technology_ai_prompts
    + health_wellness_prompts
    + climate_environment_prompts
    + finance_crypto_prompts
    + sports_fitness_prompts
    + entertainment_celebrity_prompts
    + education_careers_prompts
    + science_space_prompts
    + lifestyle_personal_dev_prompts
)

# -------- Generate tweets --------
tweets = []

all_templates = positive_templates + negative_templates

for prompt in all_prompts:
    for template in all_templates:
        tweet = template.format(prompt)
        tweets.append(tweet)

# -------- Save to CSV --------
with open("tweets.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    for tweet in tweets:
        writer.writerow([tweet])

print(f"Saved {len(tweets)} tweets to tweets.csv")
